---
title: ""
author: ""
date: ""
output: 
  html_document: 
    toc: false 
    toc_depth: 3
    toc_float: true
params:
  VSID: 0
---

```{r setup, include=FALSE,echo=FALSE,warning=FALSE}
# Setup knitr
knitr::opts_chunk$set(echo = TRUE)
# Load libraries
library(odbc)
library(tidyverse)
library(leaflet)
library(sf)
library(httr)
library(leaflet)
library(sf)
library(DT)


# Database connection
Connection = dbConnect(odbc(),Driver = "Sql Server",Server = "inp2300irmadb01\\ntwk", Database = "AKRO")

# If you need an inventory of VSIDs:
# Get the vital signs
Sql = paste("SELECT        NetworkVSName as [Vital Sign], ProjectLeadLastname+', '+ProjectLeadFirstname as [Project leader], Status
, replace(FilesDirectory,'\','/') As [Files directory]
,'<a href=https://irma.nps.gov/DataStore/Reference/Profile/'+ Convert(Varchar(20),IRMAProjectReference) + '>' + convert(varchar(40),IRMAProjectReference) + '</a>' as [Project Reference]
, Website, 'https://irma.nps.gov/DataStore/Reference/Profile/'+convert(varchar(40),IRMAProjectReference),IRMAProjectReference
--,vsid
FROM            vwVitalSignOverview
WHERE        (Status <> 'deferred') AND (NetworkID = 1)
ORDER BY Acronym, NetworkVSName",sep="")
# Vital Sign overview data frame
vs = dbGetQuery(Connection,Sql)
# knitr::kable(t(vs))


for(i in 1:nrow(vs)){
  VitalSign = vs[i,1]
  Directory = vs[i,4]
  Project = vs[i,8]
  cat("##",VitalSign,"   \n")
  cat("Shared drive: `",Directory,"`   \n")
  cat("IRMA Data Store: ",Project,"   \n")
}


```

# Data Continuity Road Map: Information Management Summary for the Arctic Inventory and Monitoring Program

## *National Park Service, Alaska Region*

Scott D. Miller\
Information Technology Specialist National Park Service, Arctic Inventory and Monitoring Network\
240 W. 5th Ave\
Anchorage, AK 99501

March 12, 2025

# Introduction

Spring 2025 has brought significant change and uncertainty to the National Park Service's Arctic Network (ARCN) Inventory and Monitoring Program. As a science-based initiative, we recognize that data forms the foundation of our understanding of park resources. Given our role as a long-term ecological monitoring program, data preservation remains our foremost priority. In times of uncertainty, it is essential to proactively manage and mitigate risks to our data. This brief provides an overview of the current state of the Arctic Network's data management resources, archives, and systems, with the goal of facilitating a seamless return to full operations in the event of any interruptions.

The ARCN relies heavily on a shared file server, an SQL Server database server, and the National Park Service's Integrated Resources Management Applications (IRMA) system for management of files and data produced by the program. A description of each of each of these systems follows:

# Data Management Systems

## Shared network drive

ARCN's shared network drive (the O:\\ drive) is the workbench for day to day data processing operations. Each Vital Sign has its own directory and ARCN personnal are expected to keep it up to date with data products as they proceed through the scientific life cycle. The O:\\ drive hosted on a server at the Fairbanks Administrative Center (FAC) and jointly administered by the Central Alaska I&M Network (CAKN) and Information Technology staff of Yukon-Charley Rivers/Gates of the Arctic. The current virtual machine UNC path is \\\\inpyugastorage\ARCN\ARCN. The file server is in a locked server room and backed up nightly. Off-site rotation of backup devices happens on a regular schedule to the Fairbanks Public Lands Information Center. Backups devices are encrypted with BitLocker. FAC IT staff and the data manager have the BitLocker passwords.

## Microsoft SQL Server

ARCN relies on three Microsoft SQL Servers for project and data management:

1.  inp2300irmadb01\ntwk. We have a database, AKRO, used for project management. This SQL Server is hosted in the NPS Denver Service Center. Management and backups are managed by NPS.

2.  inpyugamsvm01\nuna and inpyugamsvm01\nuna\_dev. Nuna is our production server and nuna_dev is the development server. Databases are in various states of development on these SQL Servers for the Lagoons, Lakes, Moose, Muskox, Shallow Lakes, Terrestrial Vegetation and Soils, Terrestrial Landscape Patterns and Dynamics and Loons monitoring protocols. Administration and backups are done by FAC and CAKN.

3.  inpakrovmais. This SQL Server is hosted by the Alaska Region GIS team and ARCN uses the Animal_Movement database to manage GPS collar data for caribou, sheep, moose and muskox Vital Signs. Administration and backups are done by the AK Regional GIS team and IT staff.

## Integrated Resource Management Applications system

IRMA is the public face of the ARCN. Each Vital Sign has a Project Reference to which products such as reports, journal articles and datasets are published. We also publish mission critical documents such as monitoring protocols, standard operating procedures, data quality standards and quality assurance plans in IRMA. Each Vital Sign Project Reference can be found by using the [ARCN Program Reference](https://irma.nps.gov/DataStore/Reference/Profile/2208369) as a starting point.

# Data Management Systems Overviews By Vital Sign

## Brown Bears

Shared drive: `O:\Monitoring\Vital Signs\Brown Bears`\
IRMA Data Store: 2210687\

## Caribou

Shared drive: `O:\Monitoring\Vital Signs\Caribou`\
IRMA Data Store: 2216435\

## Climate

Shared drive: `O:\Monitoring\Vital Signs\Climate and Weather`\
IRMA Data Store: 2210690\

## Coastal Shoreline Change

Shared drive: `O:\Monitoring\Vital Signs\Coastal Erosion`\
IRMA Data Store: 2210650\

## Dall's Sheep

Shared drive: `O:\Monitoring\Vital Signs\Dall's Sheep`\
IRMA Data Store: 2214983\

## Fire Extent and Severity

Shared drive: `O:\Monitoring\Vital Signs\Fire Extent and Severity`\
IRMA Data Store: 2219489\

## Lagoon Communities and Ecosystems

Shared drive: `O:\Monitoring\Vital Signs\Lagoon Communities and Ecosystems`\
IRMA Data Store: 2216893\

## Lake Communities and Ecosystems

Shared drive: `O:\Monitoring\Vital Signs\Lake Communities and Ecosystems`\
IRMA Data Store: 2219173\

## Landbird Monitoring

Shared drive: `O:\Monitoring\Vital Signs\Landbirds`\
IRMA Data Store: 2219895\

## Moose

Shared drive: `O:\Monitoring\Vital Signs\Moose`\
IRMA Data Store: 2222140\

## Muskox

Shared drive: `O:\Monitoring\Vital Signs\Muskox`\
IRMA Data Store: 2219896\

## Permafrost

Shared drive: `O:\Monitoring\Vital Signs\Permafrost`\
IRMA Data Store: 2220038\

## Shallow Lakes

Shared drive: `J:\Monitoring\Water_Quality_Macroinvert`\
IRMA Data Store: 2215910\

## Stream Communities and Ecosystems

Shared drive: `O:\Monitoring\Vital Signs\Stream Communities and Ecosystems`\
IRMA Data Store: 2219172\

## Terrestrial Landscape Patterns and Dynamics

Shared drive: `O:\Monitoring\Vital Signs\Terrestrial Landscape Patterns and Dynamics`\
IRMA Data Store: 2211095\

## Terrestrial Vegetation and Soils

Shared drive: `O:\Monitoring\Vital Signs\Terrestrial Vegetation and Soils`\
IRMA Data Store: 2220078\
All files are organized on the O drive in clearly labeled file hierarchy, organized by overarching utility (e.g. Data, Photos, FieldPlanning), and then by year. All final data products are on SQL server. All products for 2024 are on the O Drive.

I do not believe Dave had been in the habit of publishing data packages to IRMA for the Nodes data.

All lichen monitoring data, including Exclosures, is in this subsection of the O Drive (O:\\Monitoring\\Vital Signs\\Terrestrial Vegetation and Soils\\Data\\Lichens), as well as published to IRMA. (The only data not yet published publicly are the tissue metal concentrations from OSU, but these are backed up on the O drive.)

All files related to Red Dog are in this subset of the Drive: O:\\Monitoring\\Vital Signs\\Terrestrial Vegetation and Soils\\Data\\Lichens\\Haul Road Dataset. All but one table has been imported into SQL server, and all are available on IRMA.

## Western Yellow-billed Loons

Shared drive: `O:\Monitoring\Vital Signs\Yellow-billed Loons`\
IRMA Data Store: 2216938
