---
title: ""
author: ""
date: ""
output: 
  html_document: 
    toc: true 
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE,echo=FALSE}
VSID=18

knitr::opts_chunk$set(echo = TRUE)

library(odbc)
library(tidyverse)

Connection = dbConnect(odbc(),Driver = "Sql Server",Server = "inp2300irmadb01\\ntwk", Database = "AKRO")


# Function to fix an SQL query by replacing every comma with a newline
FixSql = function(Sql) {
  FixedSql = gsub(",", "\n,", Sql)
  FixedSql = gsub(", ", ",", FixedSql)
  return(FixedSql)
}



```

```{r, echo=FALSE}
Sql = paste("SELECT 
Acronym
,NetworkVSName AS VitalSign
,ProjectLeadLastname + ', ' + ProjectLeadFirstname as ProjectLeader
,'<a href=\"mailto:' + ProjectLeadEmail + '\">' + ProjectLeadEmail + '</a>' as Email
,ProjectLeadTelephone as Telephone
--,Convert(varchar(1000),Overview) As Overview
,Status
,Convert(Date,ImplementationDate) as ImplementationDate
,Replace(FilesDirectory,'\','\\') as Directory
,Website
,Convert(varchar(1000),Address) as Address
,'[https://irma.nps.gov/DataStore/Reference/Profile/' + Convert(varchar(20),IRMAProjectReference) + '](https://irma.nps.gov/DataStore/Reference/Profile/' + Convert(varchar(20),IRMAProjectReference) + ')' as NPSDataStore
,ProjectLeadContactID
,NetworkID
,VSID
FROM vwVitalSignOverview
WHERE (VSID = ",VSID,")",sep="")
#Sql = FixSql(Sql)
#cat(Sql)
vs = dbGetQuery(Connection,Sql)

```

# National Park Service, Arctic Inventory and Monitoring Network Vital Sign Profile: `r vs$VitalSign`

`r Sys.Date()`

# Vital Sign Details

```{r,label="VS Details",echo=FALSE}
knitr::kable(t(vs %>% select(VitalSign
 ,ProjectLeader
 ,Email
,Telephone
,Status
,ImplementationDate
,Directory
,Website
,Address
,NPSDataStore)),escape = TRUE,na.rm=TRUE)
```

# Protocols 




```{r,label="VS Protocols",echo=FALSE}

Sql = paste("SELECT [ProtocolTitle]
,[ProtocolCitation]
,[Version]
,[IRMAReferenceCode]
,[DateNarrativePublished]
,[DQSReferenceCode]
,[PIPSourceReferenceCode]
,[QAPReferenceCode]
--,[Notes]
--,[DocumentID]
--,[RecordInsertedDate]
--,[RecordInsertedBy]
--,[VSID]
,[ProtocolID]
  FROM [AKRO].[dbo].[tblVitalSignProtocols]
WHERE (VSID = ",VSID,") ORDER BY Version DESC",sep="")
protocols = dbGetQuery(Connection,Sql)

```

```{r,label="output protocols",results='asis',echo=FALSE}
for(i in 1:nrow(protocols)){
  Title = protocols[i,'ProtocolTitle']
  Citation = protocols[i,'ProtocolCitation']
  ProtocolID = protocols[i,"ProtocolID"]
  cat("## ",Citation,"  \n")
  cat("### Deliverables Schedule  \n")
  Sql = paste("SELECT  [DeliverableIdentifier]
,[Deliverable]
--,[SOP]
--,[SOPVersion]
--,[Format]
	  ,[Description]
,[Schedule]
,[Responsibility]
--,[Specifications]
--,[FileNamingScheme]
--,[DataHandling]
--,[QAQC]
--,[Archival]
--,[BuilderTasks]
--,[ValidatorTasks]
--,[CertifierTasks]
--,[DeliverableID]
--,[ProtocolID]
--,[RecordInsertedDate]
--,[RecordInsertedBy]
  FROM [AKRO].[dbo].[tblProtocolDeliverables]
 WHERE ProtocolID=",ProtocolID,sep="")
    ds = dbGetQuery(Connection,Sql)
    print(knitr::kable(ds))
}

```












```{r,echo=FALSE}
# Install and load the httr package
#install.packages("httr")
# library(httr)
# 
# # Define the URL for the GET request
# url = "https://irmaservices.nps.gov/datastore-secure/v7/rest/Profile/2285179"
# url = "https://irmaservices.nps.gov/datastore/v7/rest/QuickSearch?q=moose&format=json"
# 
# # Moose Project (ARCN)
# url = "https://irmaservices.nps.gov/datastore/v7/rest/ReferenceCodeSearch?q=2222140&format=json"
# 
# # Make the GET request
# response <- GET(url)
# 
# # Check the status code of the response
# status_code <- status_code(response)
# 
# if (status_code == 200) {
#   # Parse the JSON content from the response
#   content <- content(response, "parsed", type = "application/json")
#   
#   # Print the parsed content
#   #print(content)
#   
#   # for (i in 1:length(content$items)){
#   #   print(i)
#   # }
#   
#   Title = content[[1]][["title"]]
#   print(Title)
# } else {
#   # Handle errors
#   print(paste("Request failed with status code", status_code))
# }
```
